pub mod boolean_collection;
pub mod finite_collection;
pub mod membership_traversal;
pub mod cardinality_reduction;
pub mod disjunctive_reduction;
pub mod conjunctive_reduction;
pub mod exclusive_reduction;
pub mod boolean_array;
pub mod bitmask;
